FROM python:3.9.4-slim-buster

COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
COPY . /app
ENV FLASK_APP=views.py
ENTRYPOINT [ "python", "-m" , "flask", "run"]
CMD [ "--port", "5001"]